apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-db-chart.fullname" . }}
  labels:
    {{- include "postgres-db-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ default 5432 .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: http
  selector:
    {{- include "postgres-db-chart.selectorLabels" . | nindent 4 }}
