{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tc-server-chart.fullname" . }}-data-pvc
  labels:
    {{- include "tc-server-chart.labels" . | nindent 4 }}
spec:
  storageClassName: {{ default "teamcity-server-data-pv" .Values.persistence.volume.data.storageClassName }}
  accessModes:
    - {{ default "ReadWriteOnce" .Values.persistence.claim.accessMode }}
  resources:
    requests:
      storage: {{ default "5Gi" .Values.persistence.claim.data.requests.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tc-server-chart.fullname" . }}-logs-pvc
  labels:
  {{- include "tc-server-chart.labels" . | nindent 4 }}
spec:
  storageClassName: {{ default "teamcity-server-logs-pv" .Values.persistence.volume.logs.storageClassName }}
  accessModes:
    - {{ default "ReadWriteOnce" .Values.persistence.claim.accessMode }}
  resources:
    requests:
      storage: {{ default "1Gi" .Values.persistence.claim.logs.requests.storage }}
  {{- end }}