apiVersion: v1
kind: Service
metadata:
  name: {{ include "tc-server-chart.fullname" . }}-clusterip
  labels:
    {{- include "tc-server-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ default 8111 .Values.service.port }}
      targetPort: 8111
      protocol: TCP
      name: http
  selector:
    {{- include "tc-server-chart.selectorLabels" . | nindent 4 }}
