apiVersion: v1
kind: Service
metadata:
  name: {{ include "tc-agent-chart.fullname" . }}
  labels:
    {{- include "tc-agent-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ default 9090 .Values.service.port }}
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    {{- include "tc-agent-chart.selectorLabels" . | nindent 4 }}
